// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8QUb688o90SwSq3sVtduoy_fBKsx_AJw',
    appId: '1:998556760800:web:367a36cd8c8c869c0fee85',
    messagingSenderId: '998556760800',
    projectId: 'kvartant-1a7b7',
    authDomain: 'kvartant-1a7b7.firebaseapp.com',
    storageBucket: 'kvartant-1a7b7.firebasestorage.app',
    measurementId: 'G-L458BYYDVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WJZTbdEb2icoFhuJIHeItp0VvugOfhY',
    appId: '1:998556760800:android:29a019d77b8734010fee85',
    messagingSenderId: '998556760800',
    projectId: 'kvartant-1a7b7',
    storageBucket: 'kvartant-1a7b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBqhy2S6SRl5RBBGTpaphCwUaaV8q5Fw',
    appId: '1:998556760800:ios:bcf458e6a690c0590fee85',
    messagingSenderId: '998556760800',
    projectId: 'kvartant-1a7b7',
    storageBucket: 'kvartant-1a7b7.firebasestorage.app',
    iosBundleId: 'com.example.Kvartant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBqhy2S6SRl5RBBGTpaphCwUaaV8q5Fw',
    appId: '1:998556760800:ios:bcf458e6a690c0590fee85',
    messagingSenderId: '998556760800',
    projectId: 'kvartant-1a7b7',
    storageBucket: 'kvartant-1a7b7.firebasestorage.app',
    iosBundleId: 'com.example.Kvartant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8QUb688o90SwSq3sVtduoy_fBKsx_AJw',
    appId: '1:998556760800:web:2de31b67aaef4d340fee85',
    messagingSenderId: '998556760800',
    projectId: 'kvartant-1a7b7',
    authDomain: 'kvartant-1a7b7.firebaseapp.com',
    storageBucket: 'kvartant-1a7b7.firebasestorage.app',
    measurementId: 'G-QXLV219WR5',
  );
}
